[package]
name = "wasmtime"
authors = ["The Wasmtime Project Developers"]
version = "0.2.0"
description = "Command-line interface for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
categories = ["wasm"]
repository = "https://github.com/CraneStation/wasmtime"
edition = "2018"
default-run = "wasmtime"

[dependencies]
cranelift-codegen = { version = "0.40.0", features = ["enable-serde"] }
cranelift-native = "0.40.0"
cranelift-entity = { version = "0.40.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.40.0", features = ["enable-serde"] }
wasmtime-api = { path = "wasmtime-api", version = "0.2.0" }
wasmtime-debug = { path = "wasmtime-debug", version = "0.2.0" }
wasmtime-environ = { path = "wasmtime-environ", version = "0.2.0" }
wasmtime-interface-types = { path = "wasmtime-interface-types", version = "0.2.0" }
wasmtime-runtime = { path = "wasmtime-runtime", version = "0.2.0" }
wasmtime-jit = { path = "wasmtime-jit", version = "0.2.0" }
wasmtime-obj = { path = "wasmtime-obj", version = "0.2.0" }
wasmtime-wast = { path = "wasmtime-wast", version = "0.2.0" }
wasmtime-wasi = { path = "wasmtime-wasi", version = "0.2.0" }
wasmtime-wasi-c = { path = "wasmtime-wasi-c", version = "0.2.0", optional = true }
wasi-common = "0.2.0"
docopt = "1.0.1"
serde = { "version" = "1.0.94", features = ["derive"] }
faerie = "0.10.1"
failure = "0.1"
target-lexicon = { version = "0.4.0", default-features = false }
pretty_env_logger = "0.3.0"
file-per-thread-logger = "0.1.1"
wabt = "0.9"
libc = "0.2.60"
errno = "0.2.4"
rayon = "1.1"
wasm-webidl-bindings = "0.4"

# build.rs tests whether to enable a workaround for the libc strtof function.
[target.'cfg(target_os = "linux")'.build-dependencies]
libc = "0.2.60"

[workspace]
members = [
  "misc/wasmtime-rust",
  "misc/wasmtime-py",
]

[features]
# Temporarily disable lightbeam.
#lightbeam = ["wasmtime-environ/lightbeam", "wasmtime-jit/lightbeam"]
wasi-c = ["wasmtime-wasi-c"]
