[package]
name = "wasmtime"
version = "0.8.0"
authors = ["The Wasmtime Project Developers"]
description = "High-level API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[lib]
name = "wasmtime"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
cranelift-codegen = { version = "0.50.0", features = ["enable-serde"] }
cranelift-native = "0.50.0"
cranelift-entity = { version = "0.50.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.50.0", features = ["enable-serde"] }
cranelift-frontend = "0.50.0"
wasmtime-runtime = { path = "../runtime", version = "0.8.0" }
wasmtime-environ = { path = "../environ", version = "0.8.0" }
wasmtime-jit = { path = "../jit", version = "0.8.0" }
wasmparser = { version = "0.39.2", default-features = false }
target-lexicon = { version = "0.9.0", default-features = false }
anyhow = "1.0.19"
thiserror = "1.0.4"
region = "2.0.0"

[dev-dependencies]
# for building the examples
wat = "1.0"

[badges]
maintenance = { status = "actively-developed" }
